### ISSUE TITLE
Add battery specification

### ISSUE THREAD

**Issue by floracharbo** [floracharbo/MARL_local_electricity#10]
- find reference and add specifications for batteries that are consistent for `c_max` (max charging rate), `d_max` (max discharging rate), `cap` (total capacity), and maximum apparent power. Add reference value to documentation. 
- Possibly we could define multiple battery types that correspond to different battery specifications (e.g. Tesla, Nissan Leaf, etc.). If we cannot find exactly the specs for commercial cars we could still make reasonable assumptions of what different types might be based on academic references, etc.
- rename these variables to more explicit names.

**Comment by julie-vienne** [comment]
@floracharbo following today's discussion, I've had a better look at the electric vehicle database website.

For the Nissan Leaf, according to https://ev-database.org/uk/car/1656/Nissan-Leaf#charge-table, we have

- Charge power: 6.6 kW
- Fastcharge power: 46 kW
- Useable capacity: 39 kWh
- Vehicle-to-Home max power: 7.0 kW

This model is also used in the paper I've already referenced in the code 'Reactive power support in residential LV distribution grids through electric vehicle charging', 2015, along with other models (e.g. Toyota, Chevrolet etc).

It's one of the few that showcases a Vehicle-to-Home option (the newest Audi apparently will offer it too) but it is only providing direct current and not AC in this setting. This means that it theoretically does not make it possible to inject reactive power back into the house but this probably does not happen anyway. We're mostly expecting to be injecting reactive power into the grid and this happens with normal AC charging. 

For the fastcharge, only DC is provided so again, no reactive power possible.

**Comment by floracharbo** [comment]
> Do we also have max apparent power?

For the max apparent power, I would still calculate it as done so far based on the power factor and the max active power (= charge power). In our case, we would have apparent power = active power / power factor, with 0.95 for the power factor, which is fairly common for batteries/chargers.
In https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7544169:
“It has been selected a Mode-2 on board singlephase charger [8], whose specifications are 32 A, 230 V single-phase, 7360 W. The results will be compared in terms of harmonic distortion of the charger current, according to Std. IEEE-519 and Power Factor over 95% as it is proposed by the Std. SAE J2894.” (SAE Standard J2894: Power Quality Requirements for Plug In Vehicle Chargers. SAE: Warrendale, PA, USA, 2011)

**Comment by floracharbo** [comment]
> > Do we also have max apparent power?
> 
> For the max apparent power, I would still calculate it as done so far based on the power factor and the max active power (= charge power). In our case, we would have reactive power = active power / power factor, with 0.95 for the power factor, which is fairly common for batteries/chargers. In https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7544169: “It has been selected a Mode-2 on board singlephase charger [8], whose specifications are 32 A, 230 V single-phase, 7360 W. The results will be compared in terms of harmonic distortion of the charger current, according to Std. IEEE-519 and Power Factor over 95% as it is proposed by the Std. SAE J2894.” (SAE Standard J2894: Power Quality Requirements for Plug In Vehicle Chargers. SAE: Warrendale, PA, USA, 2011)

so are you suggesting a _maximum_ power factor of 0.95?

**Comment by julie-vienne** [comment]
> so are you suggesting a _maximum_ power factor of 0.95?

I would say we limit the max apparent power and we make sure that the active power² + reactive power² stays below this limit. We can calculate this limit with a standard power factor of 0.95 and standard max charge, yes. And then, when our agents choose their battery action, we don't constrain the power factor to allow for situations like this to happen: no active power, reactive power = max apparent power, power factor = 0.

**Comment by floracharbo** [comment]
> so are you suggesting a _maximum_ power factor of 0.95?
> I would say we limit the max apparent power and we make sure that the active power² + reactive power² stays below this limit. We can calculate this limit with a standard power factor of 0.95 and standard max charge, yes. And then, when our agents choose their battery action, we don't constrain the power factor to allow for situations like this to happen: no active power, reactive power = max apparent power, power factor = 0.

I see! Thanks. I am updating `c_max = 6.6`, `d_max = 7`, `cap = 39` [kWh] now. I will let you update the max apparent power on your branch.

**Comment by julie-vienne** [comment]
@floracharbo I think this has now been implemented. I will close it unless you still see some issues :)

**Comment by floracharbo** [comment]
yes, great!
