### ISSUE TITLE
Fix `RUN_MODE=2` and remove `RUN_MODE=3`

### ISSUE THREAD

**Issue by julie-vienne** [floracharbo/MARL_local_electricity#12]
Currently, there is a path server used if one wants to use `run_mode = 3`.

**Comment by julie-vienne** [comment]
@floracharbo as discussed, run mode 3 has been replaced by the more efficient `organise_results.py` option and run mode 2 needs fixing.

**Comment by floracharbo** [comment]
I fixed RUN_MODE = 2 but did not remove RUN_MODE = 3 as this enables me to reproduce previous plots if needed.
