### ISSUE TITLE
Fix passive homes (without manage_voltage)

### ISSUE THREAD

**Issue by julie-vienne** [floracharbo/MARL_local_electricity#28]
Many issues when `n_homesP` is not equal zero, including when trying to run with voltages and import/export penalties.
@floracharbo your help would be very appreciated :)

**Comment by julie-vienne** [comment]
@floracharbo to reproduce the error, one can run with `n_homes = 2` and `n_homesP = 2`. In `initialize_object.py` around line 322, one can see that `car['cap]` has been properly defined with length 2 (see screenshot).
![image](https://user-images.githubusercontent.com/67040704/216277250-f75165f4-ca5f-48b7-8c83-34a5015c7b6e.png)

However, later in `hedge.py`, line 394, one get a key error because the object now looks like this `{'cap': [75, 75]}` and we're trying to access the key `[home]`, where `home = 0`, which does not exist.

![image](https://user-images.githubusercontent.com/67040704/216277454-69be4a02-d40a-473f-873b-f756c941ab27.png)

**Comment by floracharbo** [comment]
ok - first it looks like l323 and l324 can be deleted in initialise_objects as it's already done l 331
(this does not solve the problem just noting this here)

**Comment by floracharbo** [comment]
you can try and add breakpoints at regular intervals between `initialise_object.py` line 322 and `hedge.py`, line 394 and examine the variable space to see when `car['cap']` was put in a dictionary like that. Start with long intervals and then gradually narrow it down so you can pinpoint where the change was made. 

But I thought that your priority for you this week was to try and to add the reactive power as a decision variable?

**Comment by julie-vienne** [comment]
> But I thought that your priority for you this week was to try and to add the reactive power as a decision variable?

Yes it is and I've started a PR. I was hoping the passive houses might be easy to fix and I can run experiments (that usually take many hours - days) while I work on the reactive power. What settings for passive houses were working when you fixed it a few weeks ago? I might try to use exactly yours to see why mine (even without voltage and agg power) are not working.

**Comment by floracharbo** [comment]
Ok cool, just checking you are not getting side-tracked by fixing every bug in the code ha. I can have a look into this later but am fixing something else now. Ran into bugs when testing your 'computational burden' PR that I am trying to investigate.

you can browse the files at the time of [my commit](https://github.com/floracharbo/private_MARL/commit/9fb73d32fe62749670ef2f801f787a98bb89e74a) if you want to see the same settings

**Comment by julie-vienne** [comment]
@floracharbo I believe the problem is around `other_prm` in `local_elec.py`. I don't perfectly know how to fix it in the function `_adjust_max_ev_loads` as I'm not sure if in this loop, `self.car['cap]` should have the entries for the flexible capacity only or also for the passive capacities?

```
            self.passive_hedge = HEDGE(
                n_homes=prm['syst']['n_homesP'],
                factors0=prm['syst']['f0'],
                clusters0=prm['syst']['clus0'],
                prm=prm,
                other_prm={'car': {'cap': prm['car']['capP']}}
            )
```

**Comment by floracharbo** [comment]
> @floracharbo I believe the problem is around `other_prm` in `local_elec.py`. I don't perfectly know how to fix it in the function `_adjust_max_ev_loads` as I'm not sure if in this loop, `self.car['cap]` should have the entries for the flexible capacity only or also for the passive capacities?
> 
> ```
>             self.passive_hedge = HEDGE(
>                 n_homes=prm['syst']['n_homesP'],
>                 factors0=prm['syst']['f0'],
>                 clusters0=prm['syst']['clus0'],
>                 prm=prm,
>                 other_prm={'car': {'cap': prm['car']['capP']}}
>             )
> ```

well spotted!

in `_replace_other_prm` in `hedge` it should be 
`                    prm[key][subkey] = subval
`                    
instead of `val`

**Comment by floracharbo** [comment]
this should solve it, let me know
