### ISSUE TITLE
Negative flexible consumption in the optimisation result

### ISSUE THREAD

**Issue by floracharbo** [floracharbo/MARL_local_electricity#30]
`[consa[load_type] >= 0 for load_type in range(self.loads['n_types'])]
`

is not respected.

This causes the assert
`            assert cons_flex[home] <= np.sum(batch_flex[home][h][1:]) + 1e-3, \
`to fail
in `local_elec`

**Comment by floracharbo** [comment]
Hi @julie-vienne, I have been working on this but don't really understand why I only started having/noticing this problem now rather than as soon as you implemented the voltage modelling. Have you every had this problem that when use model the power flows, the optimisation starts acting funny and you have errors with the flexible consumption before? If not, any idea what we may have changed since you first implemented I that may cause it?

**Comment by julie-vienne** [comment]
@floracharbo I've tried different settings and for the first time I discovered these consumption errors. For me, they started appearing when `manage_voltage = True`, `manage_agg_power = False` and the number of agents differed from 3, which had always been my standard parameter. In this case, I get the following assertion error: 

```
data_manager.py", line 506, in update_flexibility_opt
    assert np.all(np.greater(cons_flex_opt, - 1e-3)), f"cons_flex_opt {cons_flex_opt}"
AssertionError: cons_flex_opt [ 5.46908742e-06  5.05916627e-06  3.04813221e-05 -4.06564087e-02
  5.67370211e-06  5.36248951e-06  4.92247116e-06  5.67535086e-06]
```

**Comment by floracharbo** [comment]
yes this is the same problem. ok thanks.
