### ISSUE TITLE
Correct find_feasible_data timer

### ISSUE THREAD

**Issue by julie-vienne** [floracharbo/MARL_local_electricity#42]
Currently, the optimisation is timed within find_feasible_data. Ideally, we would separate them.

@floracharbo a good option to separate the find_feasible_data and the optimisation timer could be to subtract the latter from the former. What do you think?

**Comment by floracharbo** [comment]
mmmh both are fine with me. We just need to be clear that we want to count for the times when we have to attempt to do multiple optimisations in there. If you subtract the optimisation timer it would be (all in find_feasible_data including potential previous attempts at optimising) - (the latest optimisation that actually worked).

**Comment by julie-vienne** [comment]
> mmmh both are fine with me. We just need to be clear that we want to count for the times when we have to attempt to do multiple optimisations in there. If you subtract the optimisation timer it would be (all in find_feasible_data including potential previous attempts at optimising) - (the latest optimisation that actually worked).

I think that if the optimization fails, it is not recorded in `duration_opti`. That would mean that the failed attempts are only recorded in the `find_feasible_data` part and not confused with the proper optimization. Is that what you meant?

```
        if all(data_feasibles) and opt_needed and (new_data_needed or self.force_optimisation):
            try:
                start = time.time()
                res = self.optimiser.solve(self.prm)
                end = time.time()
                duration_opti = end - start
                self.timer_optimisation.append(duration_opti)
            except Exception as ex:  # if infeasible, make new data
                if str(ex)[0:6] != 'Code 3':
                    print(traceback.format_exc())
                    print(f'ex.args {ex.args}')
                data_feasible = False
            new_res = True
```

**Comment by floracharbo** [comment]
yes exactly, that is what I meant. so if you subtract the optimisation, you are only subtracting the last one that did work.

**Comment by julie-vienne** [comment]
So we could add a line below `data_feasible` such as `duration_opti = 0` to then substract zero from find feasible_data?

**Comment by floracharbo** [comment]
> 
I don't understand what you mean. `duration_opti` has no value unless the optimisation has run. And what do you mean by subtracting zero?

if you want to subtract the optimisation time I would do at the end of `find_feasible_data` something like
```
time_opti = self.timer_optimisation[-1] if new_res else 0
duration_feasible_data = end - start - time_opti
```

**Comment by julie-vienne** [comment]
I see what you mean, that makes sense. I was trying to do something similar but separating the case where we can generate results (`duration_opti = end - start`) and when the exception is raised, (`duration_opti = 0`). Then, I would have substracted this value in the upper function level.
