### ISSUE TITLE
 KeyError: 'src.post_analysis'

### ISSUE THREAD

**Issue by moonhangest** [floracharbo/MARL_local_electricity#68]
Hi, when I try to do what you did guidance to the "usage" section, after pressing run "main.py" in conda, the following error is displayed in conda's console:

runfile('F:/research/Forla/MARL_local_electricity-main/main.py', wdir='F:/research/Forla/MARL_local_electricity-main')
Reloaded modules: src, src.simulations, src.initialisation, src.utilities, src.utilities.userdeftools, src.initialisation.generate_colours, src.initialisation.get_heat_coeffs, src.initialisation.input_data, src.learners.facmac.components, src.learners.facmac.components.transforms, src.simulations.record, src.utilities.env_spaces, src.initialisation.initialise_objects, src.learners.DDPG, src.learners.DDQN, src.learners.DQN, src.learners.facmac.utils, src.learners.facmac.utils.rl_utils, src.learners.facmac.components.episode_buffer, src.learners.facmac.modules, src.learners.facmac.modules.agents.comix_agent, src.learners.facmac.modules.agents.agent, src.learners.facmac.modules.agents.mlp_agent, src.learners.facmac.modules.agents.qmix_agent, src.learners.facmac.modules.agents.rnn_agent, src.learners.facmac.modules.agents, src.learners.facmac.controllers.basic_controller, src.learners.facmac.controllers.cqmix_controller, src.learners.facmac.controllers, src.learners.facmac.modules.critics, src.learners.facmac.modules.critics.critic, src.learners.facmac.modules.critics.maddpg, src.learners.facmac.modules.mixers, src.learners.facmac.modules.mixers.qmix, src.learners.facmac.modules.mixers.vdn, src.learners.facmac.learners.learner, src.learners.facmac.modules.critics.facmac_critic, src.learners.facmac.learners.facmac_learner, src.learners.facmac.modules.critics.facmac_critic_discrete, src.learners.facmac.modules.mixers.qmix_ablations, src.learners.facmac.learners.facmac_learner_discrete, src.learners.facmac.learners.cq_learner, src.learners.facmac.learners.maddpg_learner, src.learners.facmac.learners, src.learners.Qlearning
Traceback (most recent call last):

  File "F:\research\Forla\MARL_local_electricity-main\main.py", line 13, in <module>
    from src.simulations.runner import run

  File "F:\research\Forla\MARL_local_electricity-main\src\simulations\runner.py", line 31, in <module>
    from src.post_analysis.plotting.plot_summary_no_agents import \

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 925, in _find_spec

  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec

  File "<frozen importlib._bootstrap_external>", line 1389, in _get_spec

  File "<frozen importlib._bootstrap_external>", line 1252, in __iter__

  File "<frozen importlib._bootstrap_external>", line 1239, in _recalculate

  File "<frozen importlib._bootstrap_external>", line 1235, in _get_parent_path

KeyError: 'src.post_analysis'

I have not changes any parameters and also try to find a help in internet, but unfortunately, I can't find the answer.
So Flora, can you please help me to analysis whats happen?

**Comment by floracharbo** [comment]
Hi! Is your working directory set as "F:\research\Forla\MARL_local_electricity-main"?
